[build]
  command = "mkdocs build"
  publish = "site"

[[redirects]]
  from = "/*"
  to = "/login.md"
  status = 401
  conditions = "Role = anonymous"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com;"